/**
 * FETCH-SOCIAL — turns scripts/social-urls.txt into src/data/social.ts.
 *
 * Both platforms publish an oEmbed endpoint that needs no key and no login,
 * which is the sanctioned way to read a public post's title. Nothing here
 * scrapes a page or touches a private API.
 *
 * ⚠️ TITLES ARE FETCHED, NEVER WRITTEN. Every caption in the generated file
 * is the real one from the post. If a request fails the entry is dropped and
 * reported, because a gallery captioned with plausible-sounding invented
 * titles is worse than a smaller gallery — nobody would ever spot the lie.
 *
 * ⚠️ TIKTOK THUMBNAILS ARE DOWNLOADED, NOT LINKED. TikTok's CDN URLs are
 * signed and expire, so hotlinking them ships a wall that quietly goes blank
 * in a week or two. Each one is saved to public/showcase/tiktok/. YouTube's
 * i.ytimg.com thumbnails are stable, permanent and intended to be linked, so
 * those stay remote and cost this repository nothing.
 *
 * Run:  node scripts/fetch-social.mjs
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const LIST = path.join(ROOT, "scripts", "social-urls.txt");
const OUT = path.join(ROOT, "src", "data", "social.ts");
const THUMBS = path.join(ROOT, "public", "showcase", "tiktok");

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121 Safari/537.36";

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** Both endpoints are rate-limited; a failed fetch retries before giving up. */
async function getJSON(url, tries = 3) {
  for (let i = 0; i < tries; i++) {
    try {
      const res = await fetch(url, { headers: { "User-Agent": UA, Accept: "application/json" } });
      if (res.ok) return await res.json();
      if (res.status === 404 || res.status === 401) return null; // gone or private: no retry
    } catch {
      /* network hiccup: fall through to the wait below */
    }
    await sleep(600 * (i + 1));
  }
  return null;
}

const ytId = (u) => {
  const m = u.match(/[?&]v=([\w-]{6,})/) || u.match(/\/shorts\/([\w-]{6,})/);
  return m ? m[1] : null;
};
const isShort = (u) => u.includes("/shorts/");
const ttId = (u) => (u.match(/\/(?:video|photo)\/(\d+)/) || [])[1] || null;

async function saveThumb(url, id) {
  if (!url) return null;
  try {
    const res = await fetch(url, { headers: { "User-Agent": UA } });
    if (!res.ok) return null;
    const buf = Buffer.from(await res.arrayBuffer());
    if (buf.length < 1024) return null; // a 1x1 or an error page, not a poster
    await fs.mkdir(THUMBS, { recursive: true });
    const file = `${id}.jpg`;
    await fs.writeFile(path.join(THUMBS, file), buf);
    return `/showcase/tiktok/${file}`;
  } catch {
    return null;
  }
}

const esc = (s) => String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\s+/g, " ").trim();

const run = async () => {
  const raw = await fs.readFile(LIST, "utf8");
  const urls = [...new Set(raw.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.startsWith("http")))];

  const items = [];
  const failures = [];

  for (const url of urls) {
    const isYT = url.includes("youtube.com");
    const id = isYT ? ytId(url) : ttId(url);
    if (!id) { failures.push([url, "no id in url"]); continue; }

    const endpoint = isYT
      ? `https://www.youtube.com/oembed?url=${encodeURIComponent(url)}&format=json`
      : `https://www.tiktok.com/oembed?url=${encodeURIComponent(url)}`;

    const data = await getJSON(endpoint);
    if (!data || !data.title) { failures.push([url, "no oembed response"]); continue; }

    if (isYT) {
      items.push({
        id: `yt-${id}`,
        platform: "youtube",
        videoId: id,
        title: data.title,
        author: data.author_name || "RAW Official Co.",
        // maxres does not exist for every upload; hqdefault always does.
        thumb: `https://i.ytimg.com/vi/${id}/hqdefault.jpg`,
        vertical: isShort(url),
      });
    } else {
      const local = await saveThumb(data.thumbnail_url, id);
      items.push({
        id: `tt-${id}`,
        platform: "tiktok",
        videoId: id,
        title: data.title,
        author: data.author_name || "raw_official_co",
        thumb: local,
        vertical: true, // TikTok is portrait by definition
      });
      await sleep(350); // be a polite guest on their endpoint
    }
    process.stdout.write(".");
  }

  const body = `// GENERATED by scripts/fetch-social.mjs — do not edit by hand.
// Every title below was fetched from the platform's own public oEmbed
// endpoint on ${new Date().toISOString().slice(0, 10)}; none of it is written copy.
// Re-run the script after adding URLs to scripts/social-urls.txt.

export interface SocialItem {
  id: string;
  platform: "youtube" | "tiktok";
  videoId: string;
  title: string;
  author: string;
  /** YouTube: remote and permanent. TikTok: saved locally, since their CDN links expire. */
  thumb: string | null;
  vertical: boolean;
}

export const SOCIAL: SocialItem[] = [
${items
  .map(
    (i) =>
      `  { id: "${i.id}", platform: "${i.platform}", videoId: "${i.videoId}", title: "${esc(
        i.title,
      )}", author: "${esc(i.author)}", thumb: ${i.thumb ? `"${i.thumb}"` : "null"}, vertical: ${i.vertical} },`,
  )
  .join("\n")}
];
`;

  await fs.writeFile(OUT, body, "utf8");
  console.log(`\n\n${items.length} items written to src/data/social.ts`);
  console.log(`  youtube: ${items.filter((i) => i.platform === "youtube").length}`);
  console.log(`  tiktok:  ${items.filter((i) => i.platform === "tiktok").length}`);
  console.log(`  tiktok posters saved: ${items.filter((i) => i.platform === "tiktok" && i.thumb).length}`);
  if (failures.length) {
    console.log(`\n${failures.length} could not be read (dropped rather than guessed):`);
    failures.forEach(([u, why]) => console.log(`  - ${u}  [${why}]`));
  }
};

run();
